name: List team members

on:
  workflow_dispatch:
  
jobs:
  list-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get team members
        uses: actions/github-script@v4
        with:
          script: |
            // Get Team Members
            team = await github.teams.listMembersInOrg({
              org: 'eberlemanuelorg',
              team_slug: 'admin'
            })
            console.log(team)
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
 
