name: List team members

on:
  workflow_dispatch:
  
jobs:
  list-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get team members
        uses: actions/github-script@v6
        with:
          script: |
            const teamSlug = "<team-slug>"; // Replace with the slug of your team
            const response = await github.rest.teams.listMembersInOrg({
              org: context.repo.owner,
              team_slug: teamSlug,
              per_page: 100 // Increase this value if you have more than 100 members in your team
            });
            const members = response.data.map(member => member.login);
            console.log(`Team members: ${members.join(", ")}`);
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
 
