on:
  issue_comment:                                     
    types: [created, edited]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:

      - name: Check issue comment author
        uses: actions/github-script@v6
        id: authorized-author
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          result-encoding: string
          script: |
            const teamSlug = "admin"; 
            const response = await github.rest.teams.listMembersInOrg({
              org: context.repo.owner,
              team_slug: teamSlug,
              per_page: 20
            });
            const members = response.data.map(member => member.login);
            const author = `${{ github.actor }}`
            console.log(members)
            if (members.includes(author)) {
              console.log(`${author} is in the list!`);
            } else {
              console.log(`${author} is not in the list.`);
            }
            return members.includes(author)
            
      - name: Invite member
        uses: actions/github-script@v6
        if: ${{ contains(github.event.comment.body, 'approved') && steps.authorized-author.outputs.result == 'true' }}
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
             const issueBody = await github.rest.issues.get({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
             })

             console.log(issueBody.body)

             github.rest.orgs.setMembershipForUser({
                org: 'eberlemanuelorg',
                role: 'member',
                username: 'ebeman93'
              });

              github.rest.teams.addOrUpdateMembershipForUserInOrg({
                org: 'eberlemanuelorg',
                team_slug: 'user',
                username: 'ebeman93'
              });
